### PR TITLE
upd ffmpeg to 3.3 (apr 2017)

### PR DESCRIPTION
**Pull request by kesha-antonov**

### CODE REVIEW

**Comment by killvetrov** [comment]
@kesha-antonov I noted that in loadBinary() logic there is a check of SHA1 hash of already present binary on device. If `ffmpeg` file exists and it matches the old hash, it **will not be updated**. Also, if the binary was not present on device before, then loadBinary() will re-extract ffmpeg from assets **every time**,  because the new version hash will not be recognized. I calculated SHA1 hashes for your updated binaries, and now it runs as intended. These are in CpuArch.java:
```
enum CpuArch {
    x86("7693f23bdd7e615aa47c039b153365d8b0766065"),
    ARMv7("ca5ef0448c031e3fff7f1bbeeca9f60987ff67d3"),
    NONE(null);
}
```

**Comment by kesha-antonov** [comment]
@killvetrov Nice!!!

**Comment by shyleshshy** [comment]
Hi, @kesha-antonov I just tested your update.
When I run the command "-version" or any other command it says:
CANNOT LINK EXECUTABLE DEPENDENCIES: library "libopenh264.so" not found.
I tested in Android L, arm device.
Thanks.

**Comment by kesha-antonov** [comment]
Hello, @shyleshshy !
Yes.
I do not have enough knowledge in android. We need to put both ```ffmpeg``` and ```libopenh264.so``` (https://github.com/kesha-antonov/ffmpeg-android-java/tree/master/FFmpegAndroid/assets/armeabi-v7a) in some place.
That's needed to use ffmpeg with LGPL license. 

I don't have time to solve this for now. If you have or you know how to "link" them properly I will be thankful.

**Comment by kesha-antonov** [comment]
"ffmpeg" should be able to pick up "libopenh264.so". But where to put it right I don't know

**Comment by suncj518** [comment]
is this resolved? where to put the so file to avoid error below?

CANNOT LINK EXECUTABLE DEPENDENCIES: library "libopenh264.so" not found.

**Comment by suncj518** [comment]
is this resolved? where to put the so file to avoid error below?

CANNOT LINK EXECUTABLE DEPENDENCIES: library "libopenh264.so" not found.

**Comment by aserbao** [comment]
is this resolved? CANNOT LINK EXECUTABLE “/data/user/0/com.github.hiteshsondhi88.sampleffmpeg/files/ffmpeg”: cannot locate symbol “fgets_unlocked” referenced by “/data/data/com.github.hiteshsondhi88.sampleffmpeg/files/ffmpeg”...

in vivo X20A and xiaomi9

**Pull request closed without merging**
